---
- name: Hello World Ansible Island Challenge Treasurehunt
  gather_facts: true
  hosts: all
  tasks:

    - name: Display facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Display stats
      ansible.builtin.set_stats:
        data:
          cpu_arch: "{{ ansible_facts.machine }}"
          os_family: "{{ ansible_facts.os_family }}"